name: 'Setup gRPC Web'
description: 'Download protoc and plugins compiler and add it to the PATH'
author: 'sergiocampama'
inputs:
  version:
    description: 'Version to use. Example: 23.2'
    default: '23.x'
  version-js:
    description: 'Version to use. Example: 23.2'
    default: '3.x'
  version-grpc-js:
    description: 'Version to use. Example: 23.2'
    default: '1.x'
  include-pre-releases:
    description: 'Include github pre-releases in latest version calculation'
    default: 'false'
  repo-token:
    description: 'GitHub repo token to use to avoid rate limiter'
    default: ''
runs:
  using: 'node16'
  main: 'dist/index.js'
branding:
  icon: 'box'
  color: 'green'
